# Generated by Django 3.2.5 on 2021-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='Mobile Number'),
        ),
    ]
