# Generated by Django 3.2.5 on 2021-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='invite_query',
            field=models.CharField(default='shortly', max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='invited_by',
            field=models.CharField(default='shortly', max_length=12),
        ),
    ]
